/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as UserRouteImport } from './routes/user'
import { Route as DevSpeechRouteImport } from './routes/dev.speech'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSpeechRoute = DevSpeechRouteImport.update({
  id: '/dev/speech',
  path: '/dev/speech',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guardian': typeof GuardianRoute
  '/user': typeof UserRoute
  '/dev/speech': typeof DevSpeechRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guardian': typeof GuardianRoute
  '/user': typeof UserRoute
  '/dev/speech': typeof DevSpeechRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guardian': typeof GuardianRoute
  '/user': typeof UserRoute
  '/dev/speech': typeof DevSpeechRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guardian' | '/user' | '/dev/speech'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guardian' | '/user' | '/dev/speech'
  id: '__root__' | '/' | '/guardian' | '/user' | '/dev/speech'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuardianRoute: typeof GuardianRoute
  UserRoute: typeof UserRoute
  DevSpeechRoute: typeof DevSpeechRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/speech': {
      id: '/dev/speech'
      path: '/dev/speech'
      fullPath: '/dev/speech'
      preLoaderRoute: typeof DevSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuardianRoute: GuardianRoute,
  UserRoute: UserRoute,
  DevSpeechRoute: DevSpeechRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
